# Generated by Django 5.2 on 2025-05-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='beneficiario',
            field=models.CharField(choices=[('Pionier', 'Pionier'), ('Wrangler', 'Wrangler'), ('Norton', 'Norton'), ('Vowh', 'Vowh'), ('Metal', 'Metal'), ('Prestamo', 'Préstamo')], max_length=20),
        ),
    ]
