# Generated by Django 5.2 on 2025-05-18 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_contado',
            field=models.BooleanField(default=False, help_text='Indica si el pedido es al contado (pago inmediato)'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['es_contado'], name='calendarBac_es_cont_98bff0_idx'),
        ),
    ]
