# Generated by Django 5.2 on 2025-05-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0002_pedido_es_contado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_estimada_entrega',
        ),
    ]
