# Generated by Django 5.2 on 2025-05-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0003_remove_pedido_fecha_estimada_entrega'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pedido',
            name='calendarBac_es_cont_98bff0_idx',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='es_contado',
        ),
    ]
