# Generated by Django 5.2 on 2025-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0004_remove_pedido_calendarbac_es_cont_98bff0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_contado',
            field=models.BooleanField(default=False, verbose_name='Es al contado'),
        ),
    ]
