# Generated by Django 5.2 on 2025-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0007_add_monto_final_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='monto_total_pedido',
            field=models.DecimalField(decimal_places=2, help_text='Monto total inicial del pedido', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plazo_dias',
            field=models.IntegerField(default=90),
        ),
    ]
