# Generated by Django 5.2 on 2025-05-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0008_alter_pedido_monto_total_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='identificador',
            field=models.CharField(blank=True, help_text='Código corto para identificar al proveedor (ej: PION, RED)', max_length=10),
        ),
    ]
