# Generated by Django 5.2 on 2025-05-19 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0009_proveedor_identificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['proveedor'], name='calendarBac_proveed_5462a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['proveedor', 'fecha_pedido'], name='proveedor_fecha_idx'),
        ),
    ]
