# Generated by Django 5.2 on 2025-05-19 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0010_pedido_calendarbac_proveed_5462a3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['es_contado'], name='pedido_tipo_idx'),
        ),
    ]
