# Generated by Django 5.2 on 2025-05-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0011_pedido_pedido_tipo_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='notas_internas',
        ),
    ]
