# Generated by Django 5.2 on 2025-05-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarBackend', '0012_remove_pedido_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
